name: HTML CI Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


  check-links:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress ./**/*.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}